force-app/main/default/objects/Movimiento__c/Movimiento__c.object-meta.xml
<CustomObject>
    <label>Movimiento</label>
    <nameField>
        <label>Movimiento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movimiento__c/fields/Efecto__c.field-meta.xml
<CustomField>
    <fullName>Efecto__c</fullName>
    <label>Efecto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <description>Extenal ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Identificador único fuera de Salesforce</inlineHelpText>
    <label>ExtId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movimiento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Shadow</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallOutPokemonsMovimientosTest.cls
@isTest
public with sharing class CallOutPokemonsMovimientosTest {
    @isTest static void CallOutPokemonsMovimientosTest() {
        
        Test.setMock(HttpCalloutMock.class, new MockTestMovimientos());
        
        CallOutPokemonsMovimientos bs = new CallOutPokemonsMovimientos();

        Test.startTest();
        	database.executeBatch(bs,1);
        Test.stopTest();
        
        Movimiento__c move = [
                            SELECT Id, ExtId__c, Punteria__c, Chance_de_Efecto__c, Prioridad__c,
                            Poder__c, Pp__c, Objetivo__c, Tipo__c, Efecto__c 
                            FROM Movimiento__c 
                            WHERE ExtId__c = 1
                            ];

        System.assertEquals(1, move.ExtId__c,'Error, el External Id es: ' + move.ExtId__c);
        System.assertEquals(100, move.Punteria__c,'Error, la Punteria es: ' + move.Punteria__c);
        System.assertEquals(null, move.Chance_de_Efecto__c,'Error, la Chance de Efecto es: ' +
                            move.Chance_de_Efecto__c);
        System.assertEquals(0, move.Prioridad__c,'Error, la Prioridad es: ' + move.Prioridad__c);
        System.assertEquals(40, move.Poder__c,'Error, el Poder es: ' + move.Poder__c);
        System.assertEquals(35, move.Pp__c,'Error, el Pp es: ' + move.Pp__c);
        System.assertEquals('selected-pokemon', move.Objetivo__c,'Error, el Objetivo es: ' + move.Objetivo__c);
        System.assertEquals('Normal', move.Tipo__c,'Error, el Tipo es: ' + move.Tipo__c);
        System.assertEquals('Inflicts regular damage with no additional effect.',
                            move.Efecto__c,'Error, el Efecto es: ' + move.Efecto__c);
    }
}